--liquibase formatted sql

--changeset dmitriy:1
CREATE TABLE IF NOT EXISTS image
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path  TEXT,
    file_size  BIGINT,
    media_type TEXT
);


CREATE TABLE IF NOT EXISTS users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    login        TEXT NOT NULL,

    password     TEXT NOT NULL,

    last_name    TEXT NOT NULL,

    first_name   TEXT NOT NULL,

    patronymic   TEXT NOT NULL,

    birth_date   DATE NOT NULL,

    email        TEXT NOT NULL,

    phone_number TEXT,

    image        INTEGER REFERENCES image (id),

    role         TEXT NOT NULL
);

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('admin', 'admin', 'Dmitriy', 'Astrashenya', 'Aleksandrovich', '1992-12-31', 'notRealEmail@ad.ru', null, 'ADMIN');

