--liquibase formatted sql

--changeset dmitriy:1
CREATE TABLE IF NOT EXISTS image
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path  TEXT,
    file_size  BIGINT,
    media_type TEXT
);


CREATE TABLE IF NOT EXISTS users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    login        TEXT NOT NULL,

    password     TEXT NOT NULL,

    last_name    TEXT NOT NULL,

    first_name   TEXT NOT NULL,

    patronymic   TEXT NOT NULL,

    birth_date   DATE,

    email        TEXT NOT NULL,

    phone_number TEXT,

    image        INTEGER REFERENCES image (id),

    role         TEXT NOT NULL
);

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('admin', 'admin', 'Administratorov', 'Administrator', 'Administratorovich', '1992-12-31', 'notRealAdminEmail@ad.ru', '+7(999)999-99-99', 'ADMIN');

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('login', 'password', 'Astrashenya', 'Dmitriy', 'Aleksandrovich', '1992-12-31', 'notRealEmail@ad.ru', '+7(888)888-88-88', 'USER');

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('test', 'test', 'Karpov', 'Konstantin', 'Ivanovich', '1990-05-09', 'notRealEmail@ad.ru', '+7(777)777-77-77', 'USER');

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('zolina', 'zolina123', 'Zolina', 'Elena', 'Vladimirovna', '1996-10-17', 'notRealEmail@ad.ru', null, 'USER');

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('test1', 'test1', 'Kuklina', 'Olga', 'Ivanovna', '1999-11-25', 'notRealEmail@ad.ru', 'No validation here', 'USER');

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('test2', 'test2', 'Stepanov', 'Ilya', 'Sergeevich', '1986-03-16', 'notRealEmail@ad.ru', null, 'USER');

INSERT INTO users (login, password, last_name, first_name, patronymic, birth_date, email, phone_number, role)
VALUES ('test3', 'test3', 'Polenova', 'Elizaveta', 'Evgenyevna', '1999-01-29', 'notRealEmail@ad.ru', null, 'USER');